use crate::doc_item::*;

/// Generate a markdown document from the documentation output.
/// `src_prefix` is prepended to file paths to form links, e.g. `./src/`.
pub fn format_doc_output(output: &RtDocOutput, src_prefix: &str) -> String {
    let mut md = String::new();

    md.push_str("# API Reference\n\n");
    md.push_str("*Auto-generated by verus-docgenerator*\n\n");

    for module in &output.modules {
        md.push_str(&format!("## `{}`\n\n", module.path));

        // Group items by kind within each module
        let spec_items: Vec<&RtDocItem> = module
            .items
            .iter()
            .filter(|i| matches!(i.kind, RtFnKind::Spec))
            .collect();
        let proof_items: Vec<&RtDocItem> = module
            .items
            .iter()
            .filter(|i| matches!(i.kind, RtFnKind::Proof))
            .collect();
        let exec_items: Vec<&RtDocItem> = module
            .items
            .iter()
            .filter(|i| matches!(i.kind, RtFnKind::Exec))
            .collect();

        if !spec_items.is_empty() {
            md.push_str("### Spec Functions\n\n");
            for item in &spec_items {
                format_item(&mut md, item, src_prefix);
            }
            md.push('\n');
        }

        if !proof_items.is_empty() {
            md.push_str("### Proof Functions\n\n");
            for item in &proof_items {
                format_item(&mut md, item, src_prefix);
            }
            md.push('\n');
        }

        if !exec_items.is_empty() {
            md.push_str("### Exec Functions\n\n");
            for item in &exec_items {
                format_item(&mut md, item, src_prefix);
            }
            md.push('\n');
        }
    }

    md
}

/// Format a single documentation item as a markdown list entry with a clickable link.
fn format_item(md: &mut String, item: &RtDocItem, src_prefix: &str) {
    let open_str = if item.is_open { "open " } else { "" };
    let kind_str = item.kind.as_str();

    let link = format!("{}{file}#L{line}",
        src_prefix,
        file = item.file_path,
        line = item.line_number,
    );

    md.push_str(&format!(
        "- **`{open}{kind} fn {name}`** — [{file}:{line}]({link})",
        open = open_str,
        kind = kind_str,
        name = item.name,
        file = item.file_path,
        line = item.line_number,
        link = link,
    ));

    if let Some(ref doc) = item.doc_comment {
        md.push_str(&format!("\n  > {}\n", doc));
    } else {
        md.push('\n');
    }
}
